/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hospital;

import Login.Login;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.print.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.PrintException;
/**
 *
 * @author admin
 */
public class Hospital extends javax.swing.JFrame {
    private JFrame frame;
    /**
     * Creates new form Hospital
     */
    public Hospital() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ComboBox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jtxtPossibleSideEffects = new javax.swing.JTextField();
        jtxtRef = new javax.swing.JTextField();
        jtxtDose = new javax.swing.JTextField();
        jtxtNumberTablets = new javax.swing.JTextField();
        jtxtLot = new javax.swing.JTextField();
        jtxtIssuedDate = new javax.swing.JTextField();
        jtxtExpDate = new javax.swing.JTextField();
        jtxtDailyDose = new javax.swing.JTextField();
        jtxtFurtherInformation = new javax.swing.JTextField();
        jtxtStorageAdvice = new javax.swing.JTextField();
        jtxtDrivingandUsingMachines = new javax.swing.JTextField();
        jtxtHowtoUseMedication = new javax.swing.JTextField();
        jtxtPatientId = new javax.swing.JTextField();
        jtxtPatientAddress = new javax.swing.JTextField();
        jtxtDoctorNHSNo = new javax.swing.JTextField();
        jtxtPatientName = new javax.swing.JTextField();
        jtxtDateofBirth = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setPreferredSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setText("Hospital Management System");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1380, 90));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);
        textArea.getAccessibleContext().setAccessibleParent(textArea);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 460));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 110, 330, 460));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("                      Patient Prescription");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 70));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1050, 70));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButton(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 140, -1));

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setText("Delete");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButton(evt);
            }
        });
        jPanel4.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 150, -1));

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton12.setText("Doctor");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorButton(evt);
            }
        });
        jPanel4.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 150, -1));

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton13.setText("GP Appointment");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPAppointmentButton(evt);
            }
        });
        jPanel4.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton14.setText("Patient");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientButton(evt);
            }
        });
        jPanel4.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 150, -1));

        jButton15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton15.setText("Reset");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButton(evt);
            }
        });
        jPanel4.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 140, -1));

        jButton16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton16.setText("Prescription");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrescriptionButton(evt);
            }
        });
        jPanel4.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, 140, -1));

        jButton17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton17.setText("Exit");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButton(evt);
            }
        });
        jPanel4.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 20, 120, -1));

        jButton18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton18.setText("Login");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButton(evt);
            }
        });
        jPanel4.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, 130, -1));

        jButton19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton19.setText("Print");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButton(evt);
            }
        });
        jPanel4.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 20, 130, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 570, 1460, 70));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Patient Address:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 530, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Number of Tablets:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Reference No.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Dose (mg):");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Number of Tablets:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("LOT:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Issued Date:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Exp Date:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Daily Dose:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Possible Side Effects:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        ComboBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make a Selection", "Ibuprofen", "Co-codamol", "Paracetamol", "Amiodipine" }));
        ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 200, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Further Information:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Storage Advice:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Driving and Using Machines :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("How to Use Medication:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Patient Id:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("NHS Number:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Patient Name:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Date of Birth:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, -1, -1));

        jTextField10.setText("jTextField1");
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 200, 0));

        jtxtPossibleSideEffects.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtPossibleSideEffects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PossibleSideEffectsTextField(evt);
            }
        });
        getContentPane().add(jtxtPossibleSideEffects, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 200, -1));

        jtxtRef.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReferenceNoTextfiled(evt);
            }
        });
        getContentPane().add(jtxtRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 200, -1));

        jtxtDose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtDose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoseTextFiled(evt);
            }
        });
        getContentPane().add(jtxtDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 200, -1));

        jtxtNumberTablets.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtNumberTablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberofTabletsTextField(evt);
            }
        });
        getContentPane().add(jtxtNumberTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 200, -1));

        jtxtLot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtLot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOTtextField(evt);
            }
        });
        getContentPane().add(jtxtLot, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 200, -1));

        jtxtIssuedDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtIssuedDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssuedDateTextField(evt);
            }
        });
        getContentPane().add(jtxtIssuedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 200, -1));

        jtxtExpDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtExpDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpDateTextField(evt);
            }
        });
        getContentPane().add(jtxtExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 200, -1));

        jtxtDailyDose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtDailyDose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DailyDoseTextField(evt);
            }
        });
        getContentPane().add(jtxtDailyDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 200, -1));

        jtxtFurtherInformation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtFurtherInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FurtherInformationTextField(evt);
            }
        });
        getContentPane().add(jtxtFurtherInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, 250, -1));

        jtxtStorageAdvice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtStorageAdvice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StorageAdviceTextField(evt);
            }
        });
        getContentPane().add(jtxtStorageAdvice, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, 250, -1));

        jtxtDrivingandUsingMachines.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtDrivingandUsingMachines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrivingAndUsingMachinesTextField(evt);
            }
        });
        getContentPane().add(jtxtDrivingandUsingMachines, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, 250, -1));

        jtxtHowtoUseMedication.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtHowtoUseMedication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HowToUseMachinesTextfield(evt);
            }
        });
        getContentPane().add(jtxtHowtoUseMedication, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 330, 250, -1));

        jtxtPatientId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtPatientId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientIDTextField(evt);
            }
        });
        getContentPane().add(jtxtPatientId, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, 250, -1));

        jtxtPatientAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtPatientAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientAddressTextField(evt);
            }
        });
        getContentPane().add(jtxtPatientAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 530, 250, -1));

        jtxtDoctorNHSNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtDoctorNHSNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDoctorNHSNoActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtDoctorNHSNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 410, 250, -1));

        jtxtPatientName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientNameTextField(evt);
            }
        });
        getContentPane().add(jtxtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 450, 250, -1));

        jtxtDateofBirth.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtDateofBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateOFBIrthTextField(evt);
            }
        });
        getContentPane().add(jtxtDateofBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 490, 250, -1));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number of Tablets", "Reference No", "Dose(Mg)", "Number of Tablets", "LOT:", "Issued Date:", "Exp Date", "Daily Dose", "Possible Side effects", "further Information", "Storage Advice", "Driving and Using Machines", "How to Use Medication", "Patient ID", "NHS Number", "Patient Name", "Date of Birth", "Patient Address"
            }
        ));
        jScrollPane2.setViewportView(Table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 1390, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxActionPerformed
        // TODO add your handling code here:
        if(ComboBox.getSelectedItem().equals("Ibuprofen")){
            jtxtRef.setText("Ibu8568959");
            jtxtDose.setText("2");
            jtxtNumberTablets.setText("32");
            jtxtLot.setText("561005875");
            jtxtIssuedDate.setText("06/05/2018");
            jtxtExpDate.setText("04/12/2019");
            jtxtDailyDose.setText("4");
            
            jtxtPossibleSideEffects.setText("Bleeding");
            jtxtFurtherInformation.setText("Place Dispensary");
            jtxtStorageAdvice.setText("Less than 20%");
            jtxtDrivingandUsingMachines.setText("No");
            jtxtHowtoUseMedication.setText("Use water, No Alcohol");
            jtxtPatientId.setText("P9589454");
            jtxtDoctorNHSNo.setText("646564");
            

        }
        else if(ComboBox.getSelectedItem().equals("Co-codamol")){
            jtxtRef.setText("COCO6758940");
            jtxtDose.setText("500");
            jtxtNumberTablets.setText("30");
            jtxtLot.setText("B770034");
            jtxtIssuedDate.setText("06/05/2018");
            jtxtExpDate.setText("03/02/2019");
            jtxtDailyDose.setText("2");
            
            jtxtPossibleSideEffects.setText("Dizziness");
            jtxtFurtherInformation.setText("Place Dispensary");
            jtxtStorageAdvice.setText("Less than 20%");
           jtxtDrivingandUsingMachines.setText("No");
            jtxtHowtoUseMedication.setText("Use water, No Alcohol");
            jtxtPatientId.setText("P9589454");
            jtxtDoctorNHSNo.setText("646564");
            
        }
         else if(ComboBox.getSelectedItem().equals("Paracetamol")){
            jtxtRef.setText("01729214");
            jtxtDose.setText("500");
            jtxtNumberTablets.setText("16");
            jtxtLot.setText("0204324");
            jtxtIssuedDate.setText("07/05/2018");
            jtxtExpDate.setText("04/05/2023");
            jtxtDailyDose.setText("2");
            
            jtxtPossibleSideEffects.setText("Feeling Sick");
            jtxtFurtherInformation.setText("Place Dispensary");
            jtxtStorageAdvice.setText("Less than 25%");
           jtxtDrivingandUsingMachines.setText("No");
            jtxtHowtoUseMedication.setText("Use water, No Alcohol");
            jtxtPatientId.setText("P5562454");
            jtxtDoctorNHSNo.setText("875564");
            
        }
          else if(ComboBox.getSelectedItem().equals("Amiodipine")){
            jtxtRef.setText("Am05875");
            jtxtDose.setText("5");
            jtxtNumberTablets.setText("28");
            jtxtLot.setText("8745475");
            jtxtIssuedDate.setText("06/05/2018");
            jtxtExpDate.setText("04/05/2020");
            jtxtDailyDose.setText("1");
            
            jtxtPossibleSideEffects.setText("Liver Disease");
            jtxtFurtherInformation.setText("Ability to drive may be affected");
            jtxtStorageAdvice.setText("No Special Storage");
           jtxtDrivingandUsingMachines.setText("No");
            jtxtHowtoUseMedication.setText("Use water, No Alcohol");
            jtxtPatientId.setText("P9129454");
            jtxtDoctorNHSNo.setText("6346564");
            
        }
        
          else if(ComboBox.getSelectedItem().equals("Make a Selection")){
            jtxtRef.setText("");
            jtxtDose.setText("");
            jtxtNumberTablets.setText("");
            jtxtLot.setText("");
            jtxtIssuedDate.setText("");
            jtxtExpDate.setText("");
            jtxtDailyDose.setText("");
            
            jtxtPossibleSideEffects.setText("");
            jtxtFurtherInformation.setText("");
            jtxtStorageAdvice.setText("");
           jtxtDrivingandUsingMachines.setText("");
            jtxtHowtoUseMedication.setText("");
            jtxtPatientId.setText("");
            jtxtDoctorNHSNo.setText("");
            jtxtPatientName.setText("");
            jtxtDateofBirth.setText("");
            jtxtPatientAddress.setText("");
            
        }
    }//GEN-LAST:event_ComboBoxActionPerformed

    private void PossibleSideEffectsTextField(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PossibleSideEffectsTextField
   
    }//GEN-LAST:event_PossibleSideEffectsTextField

    private void ReferenceNoTextfiled(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReferenceNoTextfiled
   
    }//GEN-LAST:event_ReferenceNoTextfiled

    private void DoseTextFiled(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoseTextFiled
     
    }//GEN-LAST:event_DoseTextFiled

    private void NumberofTabletsTextField(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberofTabletsTextField
    
    }//GEN-LAST:event_NumberofTabletsTextField

    private void LOTtextField(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOTtextField
        
    }//GEN-LAST:event_LOTtextField

    private void IssuedDateTextField(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssuedDateTextField
        
    }//GEN-LAST:event_IssuedDateTextField

    private void ExpDateTextField(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpDateTextField

    }//GEN-LAST:event_ExpDateTextField

    private void DailyDoseTextField(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DailyDoseTextField
        
    }//GEN-LAST:event_DailyDoseTextField

    private void FurtherInformationTextField(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FurtherInformationTextField
        
    }//GEN-LAST:event_FurtherInformationTextField

    private void StorageAdviceTextField(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StorageAdviceTextField
        
    }//GEN-LAST:event_StorageAdviceTextField

    private void DrivingAndUsingMachinesTextField(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrivingAndUsingMachinesTextField
  
    }//GEN-LAST:event_DrivingAndUsingMachinesTextField

    private void HowToUseMachinesTextfield(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HowToUseMachinesTextfield

    }//GEN-LAST:event_HowToUseMachinesTextfield

    private void PatientIDTextField(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientIDTextField
    
    }//GEN-LAST:event_PatientIDTextField

    private void PatientAddressTextField(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientAddressTextField
       
    }//GEN-LAST:event_PatientAddressTextField

    private void jtxtDoctorNHSNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDoctorNHSNoActionPerformed
     
    }//GEN-LAST:event_jtxtDoctorNHSNoActionPerformed

    private void PatientNameTextField(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientNameTextField
        
    }//GEN-LAST:event_PatientNameTextField

    private void DateOFBIrthTextField(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateOFBIrthTextField
       
    }//GEN-LAST:event_DateOFBIrthTextField

    private void DoctorButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorButton
          //  Login login = new Login();
          //  login.setVisible(true);
    }//GEN-LAST:event_DoctorButton

    private void DeleteButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButton
            DefaultTableModel model= (DefaultTableModel) Table.getModel();
            if(Table.getSelectedRow()== -1){
                if(Table.getRowCount()==0){
                    JOptionPane.showMessageDialog(null,"No Data to Delete","Hospital Management Systems",JOptionPane.OK_OPTION);
                }else{
                     JOptionPane.showMessageDialog(null,"Select a row  to Delete","Hospital Management Systems",JOptionPane.OK_OPTION);
                }
            }
            else{
                model.removeRow(Table.getSelectedRow());
            }
    }//GEN-LAST:event_DeleteButton

    private void UpdateButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButton
                DefaultTableModel model= (DefaultTableModel) Table.getModel();
                model.addRow(new Object[]{ComboBox.getSelectedItem().toString(),
                      jtxtRef.getText(),jtxtDose.getText(),jtxtNumberTablets.getText(),jtxtLot.getText(),jtxtIssuedDate.getText(),jtxtExpDate.getText()
                              ,jtxtDailyDose.getText(),jtxtPossibleSideEffects.getText(),jtxtFurtherInformation.getText(),jtxtStorageAdvice.getText(),jtxtDrivingandUsingMachines.getText(),jtxtHowtoUseMedication.getText(),jtxtPatientId.getText(),jtxtDoctorNHSNo.getText(),
                              jtxtPatientName.getText(),jtxtDateofBirth.getText(),jtxtPatientAddress.getText(),});
    }//GEN-LAST:event_UpdateButton

    private void ExitButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButton
     
        frame =new JFrame();
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit ?" , "Hospital Management Systems",JOptionPane.YES_NO_OPTION )== JOptionPane.YES_NO_OPTION ){
            System.exit(0);
        }
    }//GEN-LAST:event_ExitButton

    private void PrescriptionButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrescriptionButton
        String Qty1 = (jtxtRef.getText());
        String Qty2 = (jtxtDose.getText());
        String Qty3 = (jtxtNumberTablets.getText());
        String Qty4 = (jtxtLot.getText());
        String Qty5 = (jtxtDailyDose.getText());
        String Qty6 = (jtxtPossibleSideEffects.getText());
        String Qty7 = (jtxtFurtherInformation.getText());
        String Qty8 = (jtxtHowtoUseMedication.getText());
        String Qty9 = (jtxtPatientId.getText());
        String Qty10 = (jtxtPatientName.getText());
        String Qty11 = (jtxtDateofBirth.getText());
        String Qty12 = (jtxtPatientAddress.getText());
        String Qty13 = "";
        
        
        if(ComboBox.getSelectedItem().equals("Ibuprofen")){
                Qty13 ="Ibuprofen";
        }
        else if(ComboBox.getSelectedItem().equals("Co-codamol")){
             Qty13 ="Co-codamol";
            
        }
        else if(ComboBox.getSelectedItem().equals("Paracetamol")){
              Qty13 ="Paracetamol";
            
        }
        else if(ComboBox.getSelectedItem().equals("Amiodipine")){
             Qty13 ="Amiodipine";
            
        }
       
        textArea.setText("");
        textArea.append("\t\n\tHospital Management System\n"
        +"\nPatient Name:\t\t"+ Qty10
        +"\nDate of Birth:\t\t"+ Qty11
        +"\nPatient Address:\t"+ Qty12
        +"\nPrescription:\t\t"+ Qty13
        +"\n\nReference No:\t\t"+ Qty1
        +"\nDose (mg):\t\t"+ Qty2
        +"\nNumbers of Tablets:\t"+ Qty3
        +"\nLOT:\t\t"+ Qty4
        +"\nDaily Dose:\t\t"+ Qty5
        +"\nPossible Side Effects:\t"+ Qty6
        +"\nFurther Information:\t"+ Qty7
        +"\nHow to Use Medication:\t"+ Qty8
        +"\nPatient ID:\t\t"+ Qty9
        +"\n\n\tPatient Instruction We have introduced a \n\tfree text confirmation\n\t"
        +"TEXT REMINDERS FOR APPOINTMENT" );
           
    }//GEN-LAST:event_PrescriptionButton

    private void LoginButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButton
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_LoginButton

    private void GPAppointmentButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPAppointmentButton
       // Login login = new Login();
       // login.setVisible(true);
    }//GEN-LAST:event_GPAppointmentButton

    private void ResetButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButton
            jtxtRef.setText("");
            jtxtDose.setText("");
            jtxtNumberTablets.setText("");
            jtxtLot.setText("");
            jtxtIssuedDate.setText("");
            jtxtExpDate.setText("");
            jtxtDailyDose.setText("");
            
            jtxtPossibleSideEffects.setText("");
            jtxtFurtherInformation.setText("");
            jtxtStorageAdvice.setText("");
            jtxtDrivingandUsingMachines.setText("");
            jtxtHowtoUseMedication.setText("");
            jtxtPatientId.setText("");
            jtxtDoctorNHSNo.setText("");
            jtxtPatientName.setText("");
            jtxtDateofBirth.setText("");
            jtxtPatientAddress.setText("");
            ComboBox.getModel().setSelectedItem("Make a Selection");
    }//GEN-LAST:event_ResetButton

    private void PatientButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientButton
        //    Login login = new Login();
         //   login.setVisible(true);
    }//GEN-LAST:event_PatientButton

    private void printButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButton
       
        try{
                textArea.print();
        }
        catch (PrinterException ex) {
            Logger.getLogger(Hospital.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printButton

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hospital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JTable Table;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jtxtDailyDose;
    private javax.swing.JTextField jtxtDateofBirth;
    private javax.swing.JTextField jtxtDoctorNHSNo;
    private javax.swing.JTextField jtxtDose;
    private javax.swing.JTextField jtxtDrivingandUsingMachines;
    private javax.swing.JTextField jtxtExpDate;
    private javax.swing.JTextField jtxtFurtherInformation;
    private javax.swing.JTextField jtxtHowtoUseMedication;
    private javax.swing.JTextField jtxtIssuedDate;
    private javax.swing.JTextField jtxtLot;
    private javax.swing.JTextField jtxtNumberTablets;
    private javax.swing.JTextField jtxtPatientAddress;
    private javax.swing.JTextField jtxtPatientId;
    private javax.swing.JTextField jtxtPatientName;
    private javax.swing.JTextField jtxtPossibleSideEffects;
    private javax.swing.JTextField jtxtRef;
    private javax.swing.JTextField jtxtStorageAdvice;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
